version: '2'
services:
  eventpro:
    image: php:7.0-cli
    volumes:
      - /Applications/MAMP/htdocs/EventPro:/var/www
    ports:
      - "80:80"
    command: php composer.phar install --no-plugins --no-scripts && php bin/console server:run 0.0.0.0:80
    working_dir: /var/www
    links:
      - database:database
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=eventpro
      - MYSQL_USER=simo
      - MYSQL_PASSWORD=simo
      - MYSQL_ROOT_PASSWORD=root
    #volumes:
     # - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - "database:db"
    ports:
      - "8080:80"


